{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Multi-Turn Conversation: Claude Architecture Tutor\n",
    "\n",
    "A reusable conversation loop where:\n",
    "- **User types** → **Claude responds** → **loop continues**\n",
    "- System prompt configures Claude as a Claude Architecture tutor\n",
    "- Prompt caching reduces costs on repeated calls (system prompt is cached)\n",
    "- Streaming enabled for responsive output\n",
    "\n",
    "Run **Cell 3** for an interactive REPL, or **Cell 4** to replay 5 pre-written architecture questions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%pip install anthropic --quiet"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import anthropic\n",
    "\n",
    "# ── System prompt (cached across every turn) ──────────────────────────────────\n",
    "SYSTEM_PROMPT = \"\"\"\\\n",
    "You are an expert Claude Architecture Tutor. Your job is to help students deeply\n",
    "understand the key concepts behind how large language models like Claude work.\n",
    "\n",
    "Topics you teach include:\n",
    "- Transformer architecture: attention, feed-forward layers, residual connections\n",
    "- Multi-head self-attention and positional encodings\n",
    "- Tokenization: BPE, SentencePiece, why token counts matter\n",
    "- Pre-training (next-token prediction) vs. fine-tuning vs. RLHF\n",
    "- Constitutional AI (CAI): supervised learning from AI feedback + RL from AI feedback\n",
    "- Context windows: KV cache, sliding window, long-context trade-offs\n",
    "- Model families: how Haiku, Sonnet, and Opus differ in capability, speed, and cost\n",
    "- Safety techniques: harmlessness training, red-teaming, refusal calibration\n",
    "- Prompt engineering: system prompts, few-shot examples, chain-of-thought\n",
    "\n",
    "Teaching style:\n",
    "- Start with an intuitive analogy before the technical detail\n",
    "- Use concrete examples and short code snippets when helpful\n",
    "- After explaining something, ask a check-for-understanding question\n",
    "- Keep responses focused — one concept at a time\n",
    "\"\"\"\n",
    "\n",
    "client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env\n",
    "\n",
    "\n",
    "class ArchitectureTutor:\n",
    "    \"\"\"Stateful multi-turn tutor. System prompt is prompt-cached on every request.\"\"\"\n",
    "\n",
    "    def __init__(self, model: str = \"claude-opus-4-7\"):\n",
    "        self.model = model\n",
    "        self.messages: list[dict] = []\n",
    "        self._cache_hits = 0\n",
    "        self._total_input_tokens = 0\n",
    "\n",
    "    def ask(self, user_text: str) -> str:\n",
    "        \"\"\"Send a user message; stream Claude's reply; return the full text.\"\"\"\n",
    "        self.messages.append({\"role\": \"user\", \"content\": user_text})\n",
    "\n",
    "        full_reply = \"\"\n",
    "\n",
    "        with client.messages.stream(\n",
    "            model=self.model,\n",
    "            max_tokens=1024,\n",
    "            # Cache the stable system prompt so subsequent turns are cheaper\n",
    "            system=[\n",
    "                {\n",
    "                    \"type\": \"text\",\n",
    "                    \"text\": SYSTEM_PROMPT,\n",
    "                    \"cache_control\": {\"type\": \"ephemeral\"},\n",
    "                }\n",
    "            ],\n",
    "            messages=self.messages,\n",
    "        ) as stream:\n",
    "            for text in stream.text_stream:\n",
    "                print(text, end=\"\", flush=True)\n",
    "                full_reply += text\n",
    "\n",
    "            final = stream.get_final_message()\n",
    "\n",
    "        # Track cache stats\n",
    "        self._cache_hits += final.usage.cache_read_input_tokens or 0\n",
    "        self._total_input_tokens += final.usage.input_tokens or 0\n",
    "\n",
    "        self.messages.append({\"role\": \"assistant\", \"content\": full_reply})\n",
    "        print()  # newline after streamed reply\n",
    "        return full_reply\n",
    "\n",
    "    def stats(self) -> None:\n",
    "        print(f\"\\n── Cache stats ──\")\n",
    "        print(f\"  Cache-read tokens : {self._cache_hits:,}\")\n",
    "        print(f\"  Uncached input tokens: {self._total_input_tokens:,}\")\n",
    "        print(f\"  Conversation turns: {len(self.messages) // 2}\")\n",
    "\n",
    "    def reset(self) -> None:\n",
    "        self.messages.clear()\n",
    "        self._cache_hits = 0\n",
    "        self._total_input_tokens = 0\n",
    "        print(\"[Conversation reset]\")\n",
    "\n",
    "\n",
    "print(\"✓ ArchitectureTutor ready  (model: claude-opus-4-7)\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Cell 3 — Interactive Loop\n",
    "\n",
    "Type your questions at the prompt. Enter `quit`, `exit`, or `q` to stop.  \n",
    "Enter `reset` to start a fresh conversation.  \n",
    "Enter `stats` to see token-usage breakdown."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "tutor = ArchitectureTutor()\n",
    "\n",
    "print(\"Claude Architecture Tutor — type your question (or 'quit' to stop)\\n\")\n",
    "print(\"─\" * 60)\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        user_input = input(\"\\nYou: \").strip()\n",
    "    except EOFError:          # notebook kernel sends EOF on interrupt\n",
    "        break\n",
    "\n",
    "    if not user_input:\n",
    "        continue\n",
    "    if user_input.lower() in {\"quit\", \"exit\", \"q\"}:\n",
    "        tutor.stats()\n",
    "        print(\"Goodbye!\")\n",
    "        break\n",
    "    if user_input.lower() == \"reset\":\n",
    "        tutor.reset()\n",
    "        continue\n",
    "    if user_input.lower() == \"stats\":\n",
    "        tutor.stats()\n",
    "        continue\n",
    "\n",
    "    print(\"\\nClaude: \", end=\"\")\n",
    "    tutor.ask(user_input)\n",
    "    print(\"─\" * 60)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Cell 4 — Automated Test: 5 Architecture Questions\n",
    "\n",
    "Runs 5 pre-written questions in a single conversation to validate the tutor's behaviour."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "QUESTIONS = [\n",
    "    \"What is Constitutional AI and how does it differ from standard RLHF?\",\n",
    "    \"Can you walk me through how the attention mechanism works in a transformer?\",\n",
    "    \"What exactly is a context window, and what limits how large it can be?\",\n",
    "    \"Why does the word 'strawberry' sometimes count as 3 tokens? How does BPE tokenization work?\",\n",
    "    \"What are the trade-offs between Claude Haiku, Sonnet, and Opus — when should I choose each?\",\n",
    "]\n",
    "\n",
    "test_tutor = ArchitectureTutor()\n",
    "\n",
    "for i, q in enumerate(QUESTIONS, 1):\n",
    "    print(f\"\\n{'═' * 60}\")\n",
    "    print(f\"Q{i}: {q}\")\n",
    "    print(\"─\" * 60)\n",
    "    print(\"Claude: \", end=\"\")\n",
    "    test_tutor.ask(q)\n",
    "\n",
    "test_tutor.stats()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
